version: '3.8'

services:
  frontend:
    build:
      context: ./client
    container_name: gradconnect-frontend
    ports:
      # CHANGE HERE: Match the port from your vite.config.js
      - "8080:8080"
    environment:
      # This remains correct. The frontend container talks to the backend
      # container over port 5000 using the service name 'backend'.
      - VITE_API_BASE_URL=http://backend:5000
    command: npm run dev
    volumes:
      # This enables hot-reloading for the frontend
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: gradconnect-backend
    ports:
      - "5000:5000"
    env_file:
      # Best practice: Load secrets from the .env file
      - ./backend/.env
    command: npm run dev
    volumes:
      # This enables hot-reloading for the backend (if you use nodemon)
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules