
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI:-mongodb+srv://jaiveersingh23:VexJUovAP2mIFJZG@gradconnectcluster.dbvatrq.mongodb.net/?retryWrites=true&w=majority&appName=GradConnectCluster}
      - JWT_SECRET=${JWT_SECRET:-this_is_a_demo_secret}
      - FRONTEND_URL=${FRONTEND_URL:-https://grad-connect-seven.vercel.app/}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=gradconnect

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://grad-connect-seven.vercel.app/
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongodb_data:
