name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Lint (Backend)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint # make sure your backend has a lint script in package.json

      - name: Run Tests
        run: npm test # if you use Jest or other test runner — adjust if needed

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectBaseDir=server
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
